#!/usr/bin/env bash
# ~/.config/nvim/scripts/apply-colors.sh
# Reads from either pywal or matugen cache and writes lua/core/colors.lua

COLORS_LUA="$HOME/.config/nvim/lua/core/colors.lua"

# ── Try matugen first, then pywal ────────────────────────────────────────────
MATUGEN_COLORS="$HOME/.config/matugen/colors.json"
WAL_COLORS="$HOME/.cache/wal/colors"

read_pywal() {
    mapfile -t COLS < "$WAL_COLORS"
    BG="${COLS[0]}"  FG="${COLS[15]}"
    C0="${COLS[0]}"  C1="${COLS[1]}"  C2="${COLS[2]}"  C3="${COLS[3]}"
    C4="${COLS[4]}"  C5="${COLS[5]}"  C6="${COLS[6]}"  C7="${COLS[7]}"
    C8="${COLS[8]}"  C9="${COLS[9]}"  C10="${COLS[10]}" C11="${COLS[11]}"
    C12="${COLS[12]}" C13="${COLS[13]}" C14="${COLS[14]}" C15="${COLS[15]}"
}

read_matugen() {
    # matugen writes a JSON; extract dark scheme colors
    BG=$(jq -r '.colors.dark.background' "$MATUGEN_COLORS")
    FG=$(jq -r '.colors.dark.on_background' "$MATUGEN_COLORS")
    C0=$(jq -r '.colors.dark.surface' "$MATUGEN_COLORS")
    C1=$(jq -r '.colors.dark.error' "$MATUGEN_COLORS")
    C2=$(jq -r '.colors.dark.tertiary' "$MATUGEN_COLORS")
    C3=$(jq -r '.colors.dark.secondary' "$MATUGEN_COLORS")
    C4=$(jq -r '.colors.dark.primary' "$MATUGEN_COLORS")
    C5=$(jq -r '.colors.dark.secondary' "$MATUGEN_COLORS")
    C6=$(jq -r '.colors.dark.tertiary' "$MATUGEN_COLORS")
    C7=$(jq -r '.colors.dark.on_surface' "$MATUGEN_COLORS")
    C8=$(jq -r '.colors.dark.surface_variant' "$MATUGEN_COLORS")
    C9="$C1"; C10="$C2"; C11="$C3"; C12="$C4"; C13="$C5"; C14="$C6"; C15="$FG"
}

if [[ -f "$MATUGEN_COLORS" ]]; then
    read_matugen
elif [[ -f "$WAL_COLORS" ]]; then
    read_pywal
else
    echo "No color source found. Install pywal or matugen."
    exit 1
fi

# ── Write colors.lua ─────────────────────────────────────────────────────────
cat > "$COLORS_LUA" << EOF
-- AUTO-GENERATED by apply-colors.sh — do not edit manually
local M = {}

M.colors = {
    background = "$BG",
    foreground = "$FG",
    cursor     = "$FG",
    black      = "$C0",
    red        = "$C1",
    green      = "$C2",
    yellow     = "$C3",
    blue       = "$C4",
    magenta    = "$C5",
    cyan       = "$C6",
    white      = "$C7",
    brblack    = "$C8",
    brred      = "$C9",
    brgreen    = "$C10",
    bryellow   = "$C11",
    brblue     = "$C12",
    brmagenta  = "$C13",
    brcyan     = "$C14",
    brwhite    = "$C15",
}

function M.apply()
    local c = M.colors
    local hi = vim.api.nvim_set_hl

    hi(0, "Normal",        { fg = c.foreground, bg = c.background })
    hi(0, "NormalFloat",   { fg = c.foreground, bg = c.black })
    hi(0, "FloatBorder",   { fg = c.brblack,    bg = c.black })
    hi(0, "CursorLine",    { bg = c.black })
    hi(0, "CursorLineNr",  { fg = c.yellow,     bold = true })
    hi(0, "LineNr",        { fg = c.brblack })
    hi(0, "SignColumn",    { bg = c.background })
    hi(0, "ColorColumn",   { bg = c.black })
    hi(0, "VertSplit",     { fg = c.brblack })
    hi(0, "WinSeparator",  { fg = c.brblack })
    hi(0, "StatusLine",    { fg = c.foreground, bg = c.black })
    hi(0, "StatusLineNC",  { fg = c.brblack,    bg = c.black })
    hi(0, "Visual",        { bg = c.brblack })
    hi(0, "Search",        { fg = c.background, bg = c.yellow })
    hi(0, "IncSearch",     { fg = c.background, bg = c.cyan })
    hi(0, "Substitute",    { fg = c.background, bg = c.red })
    hi(0, "Comment",       { fg = c.brblack,   italic = true })
    hi(0, "String",        { fg = c.green })
    hi(0, "Number",        { fg = c.magenta })
    hi(0, "Boolean",       { fg = c.magenta })
    hi(0, "Function",      { fg = c.blue })
    hi(0, "Keyword",       { fg = c.red })
    hi(0, "Operator",      { fg = c.cyan })
    hi(0, "Type",          { fg = c.yellow })
    hi(0, "Constant",      { fg = c.magenta })
    hi(0, "Identifier",    { fg = c.foreground })
    hi(0, "PreProc",       { fg = c.cyan })
    hi(0, "Special",       { fg = c.cyan })
    hi(0, "DiagnosticError",          { fg = c.red })
    hi(0, "DiagnosticWarn",           { fg = c.yellow })
    hi(0, "DiagnosticInfo",           { fg = c.blue })
    hi(0, "DiagnosticHint",           { fg = c.cyan })
    hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.red })
    hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = c.yellow })
    hi(0, "DiffAdd",       { bg = "#1e3a2e" })
    hi(0, "DiffChange",    { bg = "#1e2a3a" })
    hi(0, "DiffDelete",    { bg = "#3a1e1e" })
    hi(0, "DiffText",      { bg = "#2a3a1e" })
    hi(0, "Pmenu",         { fg = c.foreground, bg = c.black })
    hi(0, "PmenuSel",      { fg = c.background, bg = c.blue })
    hi(0, "PmenuSbar",     { bg = c.brblack })
    hi(0, "PmenuThumb",    { bg = c.blue })
    hi(0, "Folded",        { fg = c.brblack, bg = c.black })
    hi(0, "TelescopeNormal",        { fg = c.foreground, bg = c.black })
    hi(0, "TelescopeBorder",        { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopePromptBorder",  { fg = c.blue,       bg = c.black })
    hi(0, "TelescopeResultsBorder", { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopePreviewBorder", { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopeSelection",     { fg = c.foreground, bg = c.brblack })
    hi(0, "TelescopeMatching",      { fg = c.yellow,     bold = true })
    hi(0, "NvimTreeNormal",         { fg = c.foreground, bg = c.black })
    hi(0, "NvimTreeWinSeparator",   { fg = c.brblack,    bg = c.black })
    hi(0, "NvimTreeFolderIcon",     { fg = c.blue })
    hi(0, "NvimTreeFolderName",     { fg = c.blue })
    hi(0, "NvimTreeGitDirty",       { fg = c.yellow })
    hi(0, "NvimTreeGitNew",         { fg = c.green })
    hi(0, "GitSignsAdd",    { fg = c.green })
    hi(0, "GitSignsChange", { fg = c.yellow })
    hi(0, "GitSignsDelete", { fg = c.red })
    hi(0, "IblIndent",      { fg = c.brblack })
    hi(0, "IblScope",       { fg = c.brblue })
    hi(0, "WhichKey",       { fg = c.cyan })
    hi(0, "WhichKeyGroup",  { fg = c.blue })
    hi(0, "WhichKeyFloat",  { bg = c.black })
    hi(0, "HeirlineTabBufActive",    { fg = c.background, bg = c.blue,    bold = true })
    hi(0, "HeirlineTabBufInactive",  { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlineTabBufModified",  { fg = c.yellow,     bg = c.brblack })
    hi(0, "HeirlineTabBufClose",     { fg = c.red,        bg = c.brblack })
    hi(0, "HeirlineFill",            { fg = c.brblack,    bg = c.black })
    hi(0, "HeirlineTabpageActive",   { fg = c.background, bg = c.magenta, bold = true })
    hi(0, "HeirlineTabpageInactive", { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlineMode",            { fg = c.background, bg = c.green,   bold = true })
    hi(0, "HeirlineModeInsert",      { fg = c.background, bg = c.blue,    bold = true })
    hi(0, "HeirlineModeVisual",      { fg = c.background, bg = c.magenta, bold = true })
    hi(0, "HeirlineModeCmd",         { fg = c.background, bg = c.yellow,  bold = true })
    hi(0, "HeirlineModeReplace",     { fg = c.background, bg = c.red,     bold = true })
    hi(0, "HeirlineGit",             { fg = c.magenta,    bg = c.black })
    hi(0, "HeirlineFile",            { fg = c.foreground, bg = c.black })
    hi(0, "HeirlineLSP",             { fg = c.cyan,       bg = c.black })
    hi(0, "HeirlinePos",             { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlinePosEnd",          { fg = c.background, bg = c.blue,    bold = true })
end

return M
EOF

echo "Written: $COLORS_LUA"

# ── Tell a running Neovim to reload colors ────────────────────────────────────
# If you use a Neovim socket (set NVIM_LISTEN_ADDRESS in fish config):
if [[ -n "$NVIM_LISTEN_ADDRESS" ]]; then
    nvim --server "$NVIM_LISTEN_ADDRESS" --remote-send \
        '<Esc>:lua require("core.colors").apply()<CR>' 2>/dev/null
fi
