-- AUTO-GENERATED by apply-colors.sh — do not edit manually
local M = {}

M.colors = {
    background = "#000000",
    foreground = "#e0edf5",
    cursor     = "#e0edf5",
    black      = "#000000",
    red        = "#94A4AD",
    green      = "#9CB6CD",
    yellow     = "#B2CAD4",
    blue       = "#BADBF7",
    magenta    = "#C7D4D6",
    cyan       = "#C4DEF8",
    white      = "#e0edf5",
    brblack    = "#9ca5ab",
    brred      = "#94A4AD",
    brgreen    = "#9CB6CD",
    bryellow   = "#B2CAD4",
    brblue     = "#BADBF7",
    brmagenta  = "#C7D4D6",
    brcyan     = "#C4DEF8",
    brwhite    = "#e0edf5",
}

function M.apply()
    local c = M.colors
    local hi = vim.api.nvim_set_hl

    hi(0, "Normal",        { fg = c.foreground, bg = c.background })
    hi(0, "NormalFloat",   { fg = c.foreground, bg = c.black })
    hi(0, "FloatBorder",   { fg = c.brblack,    bg = c.black })
    hi(0, "CursorLine",    { bg = c.black })
    hi(0, "CursorLineNr",  { fg = c.yellow,     bold = true })
    hi(0, "LineNr",        { fg = c.brblack })
    hi(0, "SignColumn",    { bg = c.background })
    hi(0, "ColorColumn",   { bg = c.black })
    hi(0, "VertSplit",     { fg = c.brblack })
    hi(0, "WinSeparator",  { fg = c.brblack })
    hi(0, "StatusLine",    { fg = c.foreground, bg = c.black })
    hi(0, "StatusLineNC",  { fg = c.brblack,    bg = c.black })
    hi(0, "Visual",        { bg = c.brblack })
    hi(0, "Search",        { fg = c.background, bg = c.yellow })
    hi(0, "IncSearch",     { fg = c.background, bg = c.cyan })
    hi(0, "Substitute",    { fg = c.background, bg = c.red })
    hi(0, "Comment",       { fg = c.brblack,   italic = true })
    hi(0, "String",        { fg = c.green })
    hi(0, "Number",        { fg = c.magenta })
    hi(0, "Boolean",       { fg = c.magenta })
    hi(0, "Function",      { fg = c.blue })
    hi(0, "Keyword",       { fg = c.red })
    hi(0, "Operator",      { fg = c.cyan })
    hi(0, "Type",          { fg = c.yellow })
    hi(0, "Constant",      { fg = c.magenta })
    hi(0, "Identifier",    { fg = c.foreground })
    hi(0, "PreProc",       { fg = c.cyan })
    hi(0, "Special",       { fg = c.cyan })
    hi(0, "DiagnosticError",          { fg = c.red })
    hi(0, "DiagnosticWarn",           { fg = c.yellow })
    hi(0, "DiagnosticInfo",           { fg = c.blue })
    hi(0, "DiagnosticHint",           { fg = c.cyan })
    hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.red })
    hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = c.yellow })
    hi(0, "DiffAdd",       { bg = "#1e3a2e" })
    hi(0, "DiffChange",    { bg = "#1e2a3a" })
    hi(0, "DiffDelete",    { bg = "#3a1e1e" })
    hi(0, "DiffText",      { bg = "#2a3a1e" })
    hi(0, "Pmenu",         { fg = c.foreground, bg = c.black })
    hi(0, "PmenuSel",      { fg = c.background, bg = c.blue })
    hi(0, "PmenuSbar",     { bg = c.brblack })
    hi(0, "PmenuThumb",    { bg = c.blue })
    hi(0, "Folded",        { fg = c.brblack, bg = c.black })
    hi(0, "TelescopeNormal",        { fg = c.foreground, bg = c.black })
    hi(0, "TelescopeBorder",        { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopePromptBorder",  { fg = c.blue,       bg = c.black })
    hi(0, "TelescopeResultsBorder", { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopePreviewBorder", { fg = c.brblack,    bg = c.black })
    hi(0, "TelescopeSelection",     { fg = c.foreground, bg = c.brblack })
    hi(0, "TelescopeMatching",      { fg = c.yellow,     bold = true })
    hi(0, "NvimTreeNormal",         { fg = c.foreground, bg = c.black })
    hi(0, "NvimTreeWinSeparator",   { fg = c.brblack,    bg = c.black })
    hi(0, "NvimTreeFolderIcon",     { fg = c.blue })
    hi(0, "NvimTreeFolderName",     { fg = c.blue })
    hi(0, "NvimTreeGitDirty",       { fg = c.yellow })
    hi(0, "NvimTreeGitNew",         { fg = c.green })
    hi(0, "GitSignsAdd",    { fg = c.green })
    hi(0, "GitSignsChange", { fg = c.yellow })
    hi(0, "GitSignsDelete", { fg = c.red })
    hi(0, "IblIndent",      { fg = c.brblack })
    hi(0, "IblScope",       { fg = c.brblue })
    hi(0, "WhichKey",       { fg = c.cyan })
    hi(0, "WhichKeyGroup",  { fg = c.blue })
    hi(0, "WhichKeyFloat",  { bg = c.black })
    hi(0, "HeirlineTabBufActive",    { fg = c.background, bg = c.blue,    bold = true })
    hi(0, "HeirlineTabBufInactive",  { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlineTabBufModified",  { fg = c.yellow,     bg = c.brblack })
    hi(0, "HeirlineTabBufClose",     { fg = c.red,        bg = c.brblack })
    hi(0, "HeirlineFill",            { fg = c.brblack,    bg = c.black })
    hi(0, "HeirlineTabpageActive",   { fg = c.background, bg = c.magenta, bold = true })
    hi(0, "HeirlineTabpageInactive", { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlineMode",            { fg = c.background, bg = c.green,   bold = true })
    hi(0, "HeirlineModeInsert",      { fg = c.background, bg = c.blue,    bold = true })
    hi(0, "HeirlineModeVisual",      { fg = c.background, bg = c.magenta, bold = true })
    hi(0, "HeirlineModeCmd",         { fg = c.background, bg = c.yellow,  bold = true })
    hi(0, "HeirlineModeReplace",     { fg = c.background, bg = c.red,     bold = true })
    hi(0, "HeirlineGit",             { fg = c.magenta,    bg = c.black })
    hi(0, "HeirlineFile",            { fg = c.foreground, bg = c.black })
    hi(0, "HeirlineLSP",             { fg = c.cyan,       bg = c.black })
    hi(0, "HeirlinePos",             { fg = c.foreground, bg = c.brblack })
    hi(0, "HeirlinePosEnd",          { fg = c.background, bg = c.blue,    bold = true })
end

return M
