-- ~/.config/nvim/lua/core/colors.lua
-- AUTO-GENERATED by ~/.config/nvim/scripts/apply-colors.sh
-- Do not edit manually. Re-run the script after changing wallpaper.

local M = {}

-- These values are replaced by the script
M.colors = {
	background = "#1a1b26",
	foreground = "#c0caf5",
	cursor = "#c0caf5",
	black = "#15161e",
	red = "#f7768e",
	green = "#9ece6a",
	yellow = "#e0af68",
	blue = "#7aa2f7",
	magenta = "#bb9af7",
	cyan = "#7dcfff",
	white = "#a9b1d6",
	brblack = "#414868",
	brred = "#f7768e",
	brgreen = "#9ece6a",
	bryellow = "#e0af68",
	brblue = "#7aa2f7",
	brmagenta = "#bb9af7",
	brcyan = "#7dcfff",
	brwhite = "#c0caf5",
}

function M.apply()
	local c = M.colors
	local hi = vim.api.nvim_set_hl

	-- Base UI
	hi(0, "Normal", { fg = c.foreground, bg = c.background })
	hi(0, "NormalFloat", { fg = c.foreground, bg = c.black })
	hi(0, "FloatBorder", { fg = c.brblack, bg = c.black })
	hi(0, "CursorLine", { bg = c.black })
	hi(0, "CursorLineNr", { fg = c.yellow, bold = true })
	hi(0, "LineNr", { fg = c.brblack })
	hi(0, "SignColumn", { bg = c.background })
	hi(0, "ColorColumn", { bg = c.black })
	hi(0, "VertSplit", { fg = c.brblack })
	hi(0, "WinSeparator", { fg = c.brblack })
	hi(0, "StatusLine", { fg = c.foreground, bg = c.black })
	hi(0, "StatusLineNC", { fg = c.brblack, bg = c.black })

	-- Selection & Search
	hi(0, "Visual", { bg = c.brblack })
	hi(0, "Search", { fg = c.background, bg = c.yellow })
	hi(0, "IncSearch", { fg = c.background, bg = c.cyan })
	hi(0, "Substitute", { fg = c.background, bg = c.red })

	-- Syntax (links to terminal colors — treesitter overrides specifics)
	hi(0, "Comment", { fg = c.brblack, italic = true })
	hi(0, "String", { fg = c.green })
	hi(0, "Number", { fg = c.magenta })
	hi(0, "Boolean", { fg = c.magenta })
	hi(0, "Function", { fg = c.blue })
	hi(0, "Keyword", { fg = c.red })
	hi(0, "Operator", { fg = c.cyan })
	hi(0, "Type", { fg = c.yellow })
	hi(0, "Constant", { fg = c.magenta })
	hi(0, "Identifier", { fg = c.foreground })
	hi(0, "PreProc", { fg = c.cyan })
	hi(0, "Special", { fg = c.cyan })

	-- Diagnostics
	hi(0, "DiagnosticError", { fg = c.red })
	hi(0, "DiagnosticWarn", { fg = c.yellow })
	hi(0, "DiagnosticInfo", { fg = c.blue })
	hi(0, "DiagnosticHint", { fg = c.cyan })
	hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.red })
	hi(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.yellow })

	-- Diff
	hi(0, "DiffAdd", { bg = "#1e3a2e" })
	hi(0, "DiffChange", { bg = "#1e2a3a" })
	hi(0, "DiffDelete", { bg = "#3a1e1e" })
	hi(0, "DiffText", { bg = "#2a3a1e" })

	-- Popup menu
	hi(0, "Pmenu", { fg = c.foreground, bg = c.black })
	hi(0, "PmenuSel", { fg = c.background, bg = c.blue })
	hi(0, "PmenuSbar", { bg = c.brblack })
	hi(0, "PmenuThumb", { bg = c.blue })

	-- Fold
	hi(0, "Folded", { fg = c.brblack, bg = c.black })

	-- Telescope (will be linked once telescope loads)
	hi(0, "TelescopeNormal", { fg = c.foreground, bg = c.black })
	hi(0, "TelescopeBorder", { fg = c.brblack, bg = c.black })
	hi(0, "TelescopePromptNormal", { fg = c.foreground, bg = c.black })
	hi(0, "TelescopePromptBorder", { fg = c.blue, bg = c.black })
	hi(0, "TelescopeResultsBorder", { fg = c.brblack, bg = c.black })
	hi(0, "TelescopePreviewBorder", { fg = c.brblack, bg = c.black })
	hi(0, "TelescopeSelection", { fg = c.foreground, bg = c.brblack })
	hi(0, "TelescopeMatching", { fg = c.yellow, bold = true })

	-- nvim-tree
	hi(0, "NvimTreeNormal", { fg = c.foreground, bg = c.black })
	hi(0, "NvimTreeWinSeparator", { fg = c.brblack, bg = c.black })
	hi(0, "NvimTreeFolderIcon", { fg = c.blue })
	hi(0, "NvimTreeFolderName", { fg = c.blue })
	hi(0, "NvimTreeGitDirty", { fg = c.yellow })
	hi(0, "NvimTreeGitNew", { fg = c.green })

	-- Gitsigns
	hi(0, "GitSignsAdd", { fg = c.green })
	hi(0, "GitSignsChange", { fg = c.yellow })
	hi(0, "GitSignsDelete", { fg = c.red })

	-- indent-blankline
	hi(0, "IblIndent", { fg = c.brblack })
	hi(0, "IblScope", { fg = c.brblue })

	-- which-key
	hi(0, "WhichKey", { fg = c.cyan })
	hi(0, "WhichKeyGroup", { fg = c.blue })
	hi(0, "WhichKeyDesc", { fg = c.foreground })
	hi(0, "WhichKeySeparator", { fg = c.brblack })
	hi(0, "WhichKeyFloat", { bg = c.black })

	-- Heirline tabufline / statusline (custom groups, referenced in ui.lua)
	hi(0, "HeirlineTabBufActive", { fg = c.background, bg = c.blue, bold = true })
	hi(0, "HeirlineTabBufInactive", { fg = c.foreground, bg = c.brblack })
	hi(0, "HeirlineTabBufModified", { fg = c.yellow, bg = c.brblack })
	hi(0, "HeirlineTabBufClose", { fg = c.red, bg = c.brblack })
	hi(0, "HeirlineFill", { fg = c.brblack, bg = c.black })
	hi(0, "HeirlineTabpageActive", { fg = c.background, bg = c.magenta, bold = true })
	hi(0, "HeirlineTabpageInactive", { fg = c.foreground, bg = c.brblack })

	-- Statusline sections
	hi(0, "HeirlineMode", { fg = c.background, bg = c.green, bold = true })
	hi(0, "HeirlineModeInsert", { fg = c.background, bg = c.blue, bold = true })
	hi(0, "HeirlineModeVisual", { fg = c.background, bg = c.magenta, bold = true })
	hi(0, "HeirlineModeCmd", { fg = c.background, bg = c.yellow, bold = true })
	hi(0, "HeirlineModeReplace", { fg = c.background, bg = c.red, bold = true })
	hi(0, "HeirlineGit", { fg = c.magenta, bg = c.black })
	hi(0, "HeirlineFile", { fg = c.foreground, bg = c.black })
	hi(0, "HeirlineLSP", { fg = c.cyan, bg = c.black })
	hi(0, "HeirlinePos", { fg = c.foreground, bg = c.brblack })
	hi(0, "HeirlinePosEnd", { fg = c.background, bg = c.blue, bold = true })
end

return M
